version: 1
labels:
- label: "WIP"
  title: "^(wip|WIP).*"
- label: "type: enhancement"
  title: "^feat.*"
- label: "type: fix"
  title: "^fix.*"
- label: "type: chore"
  title: "^chore.*"
- label: "type: ci"
  title: "^ci.*"
- label: "type: documentations"
  title: "^docs.*"
- label: "type: code style"
  title: "^(format|style).*"
- label: "type: refactor"
  title: "^refactor.*"
- label: "type: performance"
  title: "^perf.*"
- label: "type: test"
  title: "^test.*"