queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "label=ci: ready-to-merge"
      - or:
        - check-success=test
        - "label=type: ci"
        - "label=type: documentation"
    actions:
      queue:
        name: default