api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: POSITIVE
      prediction_raw:
      - -1.69140625
      - -1.265625
      - -0.1650390625
      - 0.85791015625
      - 1.8203125
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
