api:
  content: ''
  tags: []
gladia:
  accelerator: ''
  example:
    output:
      prediction: normal
      prediction_raw:
        hate-speech: -1.2259272336959839
        normal: 0.7596375346183777
        offensive: -0.14166447520256042
  examples: {}
  format: ''
  latency: ''
huggingface:
  link: ''
license:
  content: ''
  link: ''
  title: ''
paper:
  authors: []
  citation: ''
  link: ''
  title: ''
