summary: ''


inputs_example:
  image_url:
    default_example: "http://files.gladia.io/examples/image/image/uncolorization/landscape-pics-wallpapers.png"
    examples:
      - "http://files.gladia.io/examples/image/image/uncolorization/landscape-pics-wallpapers.jng"
      - "http://files.gladia.io/examples/image/image/uncolorization/landscape-pics-wallpapers.png"
      - "http://files.gladia.io/examples/image/image/uncolorization/landscape-pics-wallpapers.gif"
