name: Gladia Docker Hub Push

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  notify-release:
    id: notify-release
    if: |
      github.event.pull_request.merged == true
    runs-on: [self-hosted, linux, STD]
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack DH Release
        uses: rtCamp/action-slack-notify@v2.2.0
        env: 
          SLACK_CHANNEL: #releases
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: gladia-ai-ci
          SLACK_TITLE: 'New Docker Hub Release :rocket:'
          SLACK_MESSAGE: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ':rocket:'

  deploy-aipi-1:
    needs: notify-release
    runs-on: [self-hosted, linux, aipi-1]
    steps:
      - name: Notify Slack deployment
        id: notify-slack-deployment-aipi-1
        uses: rtCamp/action-slack-notify@v2.2.0
        env: 
          SLACK_CHANNEL: #releases
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: gladia-ai-ci
          SLACK_TITLE: ':rocket:New Deployment on aipi1'
          SLACK_MESSAGE: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ':rocket:'

      - name: Login to Gladia Registry
        id: login-gladia
        uses: docker/login-action@v1
        with:
          registry: docker.gladia.io
          username: ${{ secrets.DOCKER_GLADIA_USERNAME }}
          password: ${{ secrets.DOCKER_GLADIA_ACCESS_TOKEN }}
      
      - name: pull latest
        id: pull-latest
        run: docker pull docker.gladia.io/gladia:latest

      - name: stop docker gladia
        id: stop-docker-gladia
        run: docker kill gladia-aipi && docker rm gladia-aipi

      - name: start docker gladia
        id: start-docker-gladia
        run: | 
            docker run -d --name gladia-aipi \
            --gpus all --shm-size=5g \
            -p 80:8080 \
            -v /tmp/gladia:/tmp/gladia \
            -e TRITON_SERVER_PORT_HTTP=8000 \
            -e TRITON_SERVER_URL=${{ secrets.TRITON_SERVER_URL }} \
            -e TRITON_LAZY_DOWNLOAD=false \
            -e TRITON_MODELS_PATH=/tmp/gladia/triton \
            -e HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }} \
            -e STABILITY_KEY=${{ secrets.STABILITY_KEY }} \
            -e MODE=server \
            docker.gladia.io/gladia:latest

      # todo : healthcheck, notify failure

  deploy-aipi-2:
    needs: deploy-aipi-1
    id: deploy-aipi-2
    runs-on: [self-hosted, linux, aipi-2]
    steps:

      - name: Notify Slack deployment
        id: notify-slack-deployment-aipi-2
        uses: rtCamp/action-slack-notify@v2.2.0
        env: 
          SLACK_CHANNEL: #releases
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: gladia-ai-ci
          SLACK_TITLE: ':rocket:New Deployment on aipi2'
          SLACK_MESSAGE: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ':rocket:'

      - name: Login to Gladia Registry
        id: login-gladia
        uses: docker/login-action@v1
        with:
          registry: docker.gladia.io
          username: ${{ secrets.DOCKER_GLADIA_USERNAME }}
          password: ${{ secrets.DOCKER_GLADIA_ACCESS_TOKEN }}
      
      - name: pull latest
        id: pull-latest
        run: docker pull docker.gladia.io/gladia:latest

      - name: stop docker gladia
        id: stop-docker-gladia
        run: docker kill gladia-aipi && docker rm gladia-aipi

      - name: start docker gladia
        id: start-docker-gladia
        run: | 
            docker run -d \
            --name gladia-aipi \
            --gpus all \
            --shm-size=5g \
            -p 80:8080 \
            -v /tmp/gladia:/tmp/gladia \
            -e TRITON_SERVER_PORT_HTTP=8000 \
            -e TRITON_SERVER_URL=${{ secrets.TRITON_SERVER_URL }} \
            -e TRITON_LAZY_DOWNLOAD=false \
            -e TRITON_MODELS_PATH=/tmp/gladia/triton \
            -e HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }} \
            -e STABILITY_KEY=${{ secrets.STABILITY_KEY }} \
            -e MODE=server \
            docker.gladia.io/gladia:latest

  notify-deployments:
    needs: [deploy-aipi-2, deploy-aipi-2]
    id: notify-deployments-end
    runs-on: [self-hosted, linux, STD]
    steps:
      - uses: actions/checkout@v2
      - name: Notify Slack Deployment done
        uses: rtCamp/action-slack-notify@v2.2.0
        env: 
          SLACK_CHANNEL: #releases
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: gladia-ai-ci
          SLACK_TITLE: ':rocket:Deployment done '
          SLACK_MESSAGE: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ':rocket:'
      
      
  # todo : healthcheck, notify failure
