name: Gladia Builder

on:
  workflow_run:
    workflows: ["PR Linter"]
    types:
      - completed

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  lint:
    if: github.event_name == 'pull_request'
    uses: gladiaio/gladia/.github/workflows/pr-linter.yml@main

  build:

    if: |-
      ${{ 
        ( !contains(github.event.pull_request.labels.*.name, 'ci') ||
          !contains(github.event.pull_request.labels.*.name, 'doc') ) &&
        github.event.workflow_run.conclusion == 'success'
      }}
    runs-on: [self-hosted, linux, STD]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to NVCR Registry
        uses: docker/login-action@v2
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_ACCESS_TOKEN }}

      - name: Build Gladia image
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./src
        run: docker build -t docker.gladia.io/gladia:ci-${{ github.event.pull_request.number }} -f gpu.Dockerfile .

      - name: Login to Docker Gladia
        uses: docker/login-action@v1
        with:
          registry: docker.gladia.io
          username: ${{ secrets.DOCKER_GLADIA_USERNAME }}
          password: ${{ secrets.DOCKER_GLADIA_ACCESS_TOKEN }}

      - name: Push build PR ${{ github.event.pull_request.number }} to gladia registry
        run: docker push docker.gladia.io/gladia:ci-${{ github.event.pull_request.number }}

  test:
    needs: build
    runs-on: [self-hosted, linux, GPU]
    steps:
      - name: Get GPU ID
        id: gpuid
        run: |
          N=$(echo ${{ runner.name }} )
          if [[ ${N: -1} =~ [0-9] ]]; then 
            echo ::set-output name=gpuid::$(echo ${N: -1} )
          else 
            echo "Error : unexpected GPU ID"
            exit 1
          fi

      - name: Start Gladia Container
        run: | 
          docker run -d \
          --cpus 14 --memory 32g --gpus all --shm-size=5g \
          -e IS_CI="True" -e NVIDIA_VISIBLE_DEVICES=${{steps.gpuid.outputs.gpuid}} -e CUDA_VISIBLE_DEVICES=${{steps.gpuid.outputs.gpuid}} \
          -p ${{steps.gpuid.outputs.gpuid}}8000:8000 \
          -v /data/volumes/models:/tmp/gladia/models \
          --name jlmagouille-${{ github.event.pull_request.number	}} docker.gladia.io/gladia:ci-${{ github.event.pull_request.number }}

      - name: Gladia container readiness
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 36
          retry_on: error
          command: curl http://localhost:${{steps.gpuid.outputs.gpuid}}8000/v2/health/ready --connect-timeout 5

      - name: Give it 5s to make sure it is ready
        run: sleep 5s
        
      - name: Test
        id: test
        run: | 
          docker exec -i \
          -e PR=${{ github.event.pull_request.number }} -e GHT=${{ secrets.GITHUB_TOKEN }} \
          jlmagouille-${{ github.event.pull_request.number }} \
          /bin/bash -c 'echo $PR; eval "$(micromamba shell hook --shell=bash)" && micromamba activate server && cd /app/unit-test/ && python3 test.py'

      - name: Logs
        if: always()
        run: |
           docker logs jlmagouille-${{ github.event.pull_request.number }}

      - name: Clean Docker Test Env
        if: always()
        continue-on-error: True
        run: |
          docker stop jlmagouille-${{ github.event.pull_request.number }}
          docker rm jlmagouille-${{ github.event.pull_request.number }}
