name: Gladia Base Builder

on:
  schedule:
    cron: '30 3 * * 0'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:

  build:
    runs-on: [self-hosted, linux, STD]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to NVCR Registry
        uses: docker/login-action@v2
        with:
          registry: nvcr.io
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_ACCESS_TOKEN }}

      - name: Build Gladia Base image
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./src
        run: docker build --no-cache -t docker.gladia.io/gladia-base:latest -f base.Dockerfile .

      - name: Login to Docker Gladia
        uses: docker/login-action@v1
        with:
          registry: docker.gladia.io
          username: ${{ secrets.DOCKER_GLADIA_USERNAME }}
          password: ${{ secrets.DOCKER_GLADIA_ACCESS_TOKEN }}

      - name: Push new base latest to gladia registry
        run: docker push docker.gladia.io/gladia-base:latest