name: Gladia Docker Hub Push

on:
  push:
    branches: [ main ]

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  promote:
    runs-on: [self-hosted, linux, STD]
    steps:
      - name: Tag built image to latest
        run: docker tag gladiaio/gladia:ci-${{ github.sha }} gladiaio/gladia:latest

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # - name: Push latest to DH regsitry
      #   run: docker push gladiaio/gladia:latest
