name: "PR Linter"
on:
  workflow_call:

jobs:
  main:
    name: Validate PR title
    runs-on: [self-hosted, linux, STD]
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}